language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-29


# code coverage
after_success:
  - bash <(curl -s --retry 10 https://codecov.io/bash)

script:
  - ./gradlew lib:assembleDebug lib:testDebugUnitTest lib:jacocoTestReport